name: Deploy to Astro
on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow
          pip install -r requirements.txt
      
      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.4
        with:
          deployment-id: ${{ secrets.ASTRO_DEPLOYMENT_ID }}
          api-token: ${{ secrets.ASTRO_API_TOKEN }}
          force: true  # Force deploy even if there are no changes detected 